# Generated by Django 3.2.14 on 2022-07-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_log_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='approved_for_academic',
            field=models.BooleanField(default=False),
        ),
    ]
