# Generated by Django 3.2.14 on 2022-07-23 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220722_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taker', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='qustionnare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='polls.questionnare'),
        ),
    ]
